def PSIIlabels(self):
    self.PSII_anchor_text = {"supercomplex" : (13, 177), "Core" : (720, 173) , "LHCII" : (365, 18), "CP24" : (338, 202), "CP26" : (369, 315), "CP29" : (749, 300)}
    space = 12
    self.image_PSII_on_canvas_text_PSII_supercomplex = self.canvas_PSII.create_text(self.PSII_anchor_text["supercomplex"][0], self.PSII_anchor_text["supercomplex"][1], anchor="nw")
    self.canvas_PSII.itemconfig(self.image_PSII_on_canvas_text_PSII_supercomplex, text = "PSII supercomplex", font = ("Helvetica", 8))
    self.image_PSII_on_canvas_text_PSII_supercomplex_Chl_a = self.canvas_PSII.create_text(self.PSII_anchor_text["supercomplex"][0], self.PSII_anchor_text["supercomplex"][1] + space, anchor="nw")
    string = "Chl a: %.0f" % (self.LEAF.thylakoidMembrane.PSII.N_Chl_a*2)
    self.canvas_PSII.itemconfig(self.image_PSII_on_canvas_text_PSII_supercomplex_Chl_a, text = string, font = ("Helvetica", 8))
    self.image_PSII_on_canvas_text_PSII_supercomplex_Chl_b = self.canvas_PSII.create_text(self.PSII_anchor_text["supercomplex"][0], self.PSII_anchor_text["supercomplex"][1] + 2*space, anchor="nw")
    string = "Chl b: %.0f" % (self.LEAF.thylakoidMembrane.PSII.N_Chl_b*2)
    self.canvas_PSII.itemconfig(self.image_PSII_on_canvas_text_PSII_supercomplex_Chl_b, text = string, font = ("Helvetica", 8))

    self.image_PSII_on_canvas_text_LHCII = self.canvas_PSII.create_text(self.PSII_anchor_text["LHCII"][0], self.PSII_anchor_text["LHCII"][1], anchor="nw")
    self.canvas_PSII.itemconfig(self.image_PSII_on_canvas_text_LHCII, text = "LHCII", font = ("Helvetica", 8))
    self.image_PSII_on_canvas_text_PSII_LHCII_Chl_a = self.canvas_PSII.create_text(self.PSII_anchor_text["LHCII"][0], self.PSII_anchor_text["LHCII"][1] + space, anchor="nw")
    string = "Chl a: %.0f" % (self.LEAF.thylakoidMembrane.PSII.LHCII.N_Chl_a)
    self.canvas_PSII.itemconfig(self.image_PSII_on_canvas_text_PSII_LHCII_Chl_a, text = string, font = ("Helvetica", 8))
    self.image_PSII_on_canvas_text_PSII_LHCII_Chl_b = self.canvas_PSII.create_text(self.PSII_anchor_text["LHCII"][0], self.PSII_anchor_text["LHCII"][1] + 2*space, anchor="nw")
    string = "Chl b: %.0f" % (self.LEAF.thylakoidMembrane.PSII.LHCII.N_Chl_b)
    self.canvas_PSII.itemconfig(self.image_PSII_on_canvas_text_PSII_LHCII_Chl_b, text = string, font = ("Helvetica", 8))
    self.image_PSII_on_canvas_text_PSII_n_LHCII = self.canvas_PSII.create_text(self.PSII_anchor_text["LHCII"][0], self.PSII_anchor_text["LHCII"][1] + 3*space, anchor="nw")
    string = "n: %.3f" % (self.LEAF.thylakoidMembrane.PSII.n_LHCII)
    self.canvas_PSII.itemconfig(self.image_PSII_on_canvas_text_PSII_n_LHCII, text = string, font = ("Helvetica", 8))

    self.image_PSII_on_canvas_text_Core = self.canvas_PSII.create_text(self.PSII_anchor_text["Core"][0], self.PSII_anchor_text["Core"][1], anchor="nw")
    self.canvas_PSII.itemconfig(self.image_PSII_on_canvas_text_Core, text = "Core", font = ("Helvetica", 8))
    self.image_PSII_on_canvas_text_PSII_Core_Chl_a = self.canvas_PSII.create_text(self.PSII_anchor_text["Core"][0], self.PSII_anchor_text["Core"][1] + space, anchor="nw")
    string = "Chl a: %.0f" % (self.LEAF.thylakoidMembrane.PSII.Core.N_Chl_a)
    self.canvas_PSII.itemconfig(self.image_PSII_on_canvas_text_PSII_Core_Chl_a, text = string, font = ("Helvetica", 8))
    self.image_PSII_on_canvas_text_PSII_Core_Chl_b = self.canvas_PSII.create_text(self.PSII_anchor_text["Core"][0], self.PSII_anchor_text["Core"][1] + 2*space, anchor="nw")
    string = "Chl b: %.0f" % (self.LEAF.thylakoidMembrane.PSII.Core.N_Chl_b)
    self.canvas_PSII.itemconfig(self.image_PSII_on_canvas_text_PSII_Core_Chl_b, text = string, font = ("Helvetica", 8))

    self.image_PSII_on_canvas_text_PSII_n_Core = self.canvas_PSII.create_text(self.PSII_anchor_text["Core"][0], self.PSII_anchor_text["Core"][1] + 3*space, anchor="nw")
    string = "n: %.0f" % (self.LEAF.thylakoidMembrane.PSII.n_Core)
    self.canvas_PSII.itemconfig(self.image_PSII_on_canvas_text_PSII_n_Core, text = string, font = ("Helvetica", 8))
    self.image_PSII_on_canvas_text_CP24 = self.canvas_PSII.create_text(self.PSII_anchor_text["CP24"][0], self.PSII_anchor_text["CP24"][1], anchor="nw")
    self.canvas_PSII.itemconfig(self.image_PSII_on_canvas_text_CP24, text = "CP24", font = ("Helvetica", 8))
    self.image_PSII_on_canvas_text_PSII_CP24_Chl_a = self.canvas_PSII.create_text(self.PSII_anchor_text["CP24"][0], self.PSII_anchor_text["CP24"][1] + space, anchor="nw")
    string = "Chl a: %.0f" % (self.LEAF.thylakoidMembrane.PSII.minors.CP24.N_Chl_a)
    self.canvas_PSII.itemconfig(self.image_PSII_on_canvas_text_PSII_CP24_Chl_a, text = string, font = ("Helvetica", 8))

    self.image_PSII_on_canvas_text_PSII_CP24_Chl_b = self.canvas_PSII.create_text(self.PSII_anchor_text["CP24"][0], self.PSII_anchor_text["CP24"][1] + 2*space, anchor="nw")
    string = "Chl b: %.0f" % (self.LEAF.thylakoidMembrane.PSII.minors.CP24.N_Chl_b)
    self.canvas_PSII.itemconfig(self.image_PSII_on_canvas_text_PSII_CP24_Chl_b, text = string, font = ("Helvetica", 8))
    self.image_PSII_on_canvas_text_PSII_n_CP24 = self.canvas_PSII.create_text(self.PSII_anchor_text["CP24"][0], self.PSII_anchor_text["CP24"][1] + 3*space, anchor="nw")
    string = "n: %.0f" % (self.LEAF.thylakoidMembrane.PSII.n_CP24)
    self.canvas_PSII.itemconfig(self.image_PSII_on_canvas_text_PSII_n_CP24, text = string, font = ("Helvetica", 8))
    self.image_PSII_on_canvas_text_CP26 = self.canvas_PSII.create_text(self.PSII_anchor_text["CP26"][0], self.PSII_anchor_text["CP26"][1], anchor="nw")
    self.canvas_PSII.itemconfig(self.image_PSII_on_canvas_text_CP26, text = "CP26", font = ("Helvetica", 8))

    self.image_PSII_on_canvas_text_PSII_CP26_Chl_a = self.canvas_PSII.create_text(self.PSII_anchor_text["CP26"][0], self.PSII_anchor_text["CP26"][1] + space, anchor="nw")
    string = "Chl a: %.0f" % (self.LEAF.thylakoidMembrane.PSII.minors.CP26.N_Chl_a)
    self.canvas_PSII.itemconfig(self.image_PSII_on_canvas_text_PSII_CP26_Chl_a, text = string, font = ("Helvetica", 8))
    self.image_PSII_on_canvas_text_PSII_CP26_Chl_b = self.canvas_PSII.create_text(self.PSII_anchor_text["CP26"][0], self.PSII_anchor_text["CP26"][1] + 2*space, anchor="nw")
    string = "Chl b: %.0f" % (self.LEAF.thylakoidMembrane.PSII.minors.CP26.N_Chl_b)
    self.canvas_PSII.itemconfig(self.image_PSII_on_canvas_text_PSII_CP26_Chl_b, text = string, font = ("Helvetica", 8))
    self.image_PSII_on_canvas_text_PSII_n_CP26 = self.canvas_PSII.create_text(self.PSII_anchor_text["CP26"][0], self.PSII_anchor_text["CP26"][1] + 3*space, anchor="nw")
    string = "n: %.0f" % (self.LEAF.thylakoidMembrane.PSII.n_CP26)
    self.canvas_PSII.itemconfig(self.image_PSII_on_canvas_text_PSII_n_CP26, text = string, font = ("Helvetica", 8))

    self.image_PSII_on_canvas_text_CP29 = self.canvas_PSII.create_text(self.PSII_anchor_text["CP29"][0], self.PSII_anchor_text["CP29"][1], anchor="nw")
    self.canvas_PSII.itemconfig(self.image_PSII_on_canvas_text_CP29, text = "CP29", font = ("Helvetica", 8))
    self.image_PSII_on_canvas_text_PSII_CP29_Chl_a = self.canvas_PSII.create_text(self.PSII_anchor_text["CP29"][0], self.PSII_anchor_text["CP29"][1] + space, anchor="nw")
    string = "Chl a: %.0f" % (self.LEAF.thylakoidMembrane.PSII.minors.CP29.N_Chl_a)
    self.canvas_PSII.itemconfig(self.image_PSII_on_canvas_text_PSII_CP29_Chl_a, text = string, font = ("Helvetica", 8))
    self.image_PSII_on_canvas_text_PSII_CP29_Chl_b = self.canvas_PSII.create_text(self.PSII_anchor_text["CP29"][0], self.PSII_anchor_text["CP29"][1] + 2*space, anchor="nw")
    string = "Chl b: %.0f" % (self.LEAF.thylakoidMembrane.PSII.minors.CP29.N_Chl_b)
    self.canvas_PSII.itemconfig(self.image_PSII_on_canvas_text_PSII_CP29_Chl_b, text = string, font = ("Helvetica", 8))
    self.image_PSII_on_canvas_text_PSII_n_CP29 = self.canvas_PSII.create_text(self.PSII_anchor_text["CP29"][0], self.PSII_anchor_text["CP29"][1] + 3*space, anchor="nw")
    string = "n: %.0f" % (self.LEAF.thylakoidMembrane.PSII.n_CP29)
    self.canvas_PSII.itemconfig(self.image_PSII_on_canvas_text_PSII_n_CP29, text = string, font = ("Helvetica", 8))